version: '3.8'

services:

  nodejs_web:
    build:
      context: nodejs_web
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    environment:
      - HOST=0.0.0.0
    command: tail -F anything
    user: "${ID_USER}:${ID_GROUP}"
    ports:
      - "9000:9000" # for vite dev websocket
    restart: unless-stopped

  nodejs_electron:
    build:
      context: nodejs_electron
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    environment:
      - HOST=0.0.0.0
    command: tail -F anything
    user: "${ID_USER}:${ID_GROUP}"
    restart: unless-stopped

  nodejs_cordova:
    build:
      context: nodejs_cordova
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    environment:
      - HOST=0.0.0.0
    command: tail -F anything
    user: "${ID_USER}:${ID_GROUP}"
    restart: unless-stopped

  nginx_dev:
    build:
      context: nginx_dev
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    restart: unless-stopped
    ports:
      - ${PORT_NGINX_DEV}:80

  nginx_prod:
    build:
      context: nginx_prod
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    restart: unless-stopped
    ports:
      - ${PORT_NGINX_PROD}:80

  nginx_electron:
    build:
      context: nginx_prod
    working_dir: /usr/share/nginx/front
    volumes:
      - ../front:/usr/share/nginx/front
    restart: unless-stopped
    ports:
      - ${PORT_NGINX_ELECTRON}:80
